Repository seoiiwon/gaechuck-android, pull requests merged in 2025-03, with the labels that each got.

#36 Feature/#31 - MasterMode API Connect (Business, Lose, Rent)
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/gaechuck/MainActivity.kt
  app/src/main/java/com/example/gaechuck/api/ApiService.kt
  app/src/main/java/com/example/gaechuck/data/request/BusinessCreateRequest.kt
  app/src/main/java/com/example/gaechuck/data/request/BusinessDeleteRequest.kt
  app/src/main/java/com/example/gaechuck/data/request/LoseCreateRequest.kt
  app/src/main/java/com/example/gaechuck/data/request/LoseDeleteRequest.kt
  app/src/main/java/com/example/gaechuck/data/request/RentCreateRequest.kt
  app/src/main/java/com/example/gaechuck/data/request/RentDeleteRequest.kt
  app/src/main/java/com/example/gaechuck/data/response/PostRentCreateResponse.kt
  app/src/main/java/com/example/gaechuck/data/response/PostRentDeleteResponse.kt
  app/src/main/java/com/example/gaechuck/repository/BusinessRepository.kt
  app/src/main/java/com/example/gaechuck/repository/LoseRepository.kt
  app/src/main/java/com/example/gaechuck/repository/RentRepository.kt
  app/src/main/java/com/example/gaechuck/ui/business/BusinessActivity.kt
  app/src/main/java/com/example/gaechuck/ui/business/BusinessDetailFragment.kt
  app/src/main/java/com/example/gaechuck/ui/business/BusinessMainFragment.kt
  app/src/main/java/com/example/gaechuck/ui/business/BusinessWriteActivity.kt
  app/src/main/java/com/example/gaechuck/ui/business/adapter/BusinessAdapter.kt
  app/src/main/java/com/example/gaechuck/ui/business/viewmodel/BusinessViewModel.kt
  app/src/main/java/com/example/gaechuck/ui/login/viewmodel/LoginViewModel.kt
  app/src/main/java/com/example/gaechuck/ui/lose/LoseActivity.kt
  app/src/main/java/com/example/gaechuck/ui/lose/LoseDetailFragment.kt
  app/src/main/java/com/example/gaechuck/ui/lose/LoseMainFragment.kt
  app/src/main/java/com/example/gaechuck/ui/lose/LoseUrlChangeActivity.kt
  app/src/main/java/com/example/gaechuck/ui/lose/LoseWriteActivity.kt
  app/src/main/java/com/example/gaechuck/ui/lose/adapter/GridAdapter.kt
  app/src/main/java/com/example/gaechuck/ui/lose/adapter/LoseAdapter.kt
  app/src/main/java/com/example/gaechuck/ui/lose/viewmodel/LoseViewModel.kt
  app/src/main/java/com/example/gaechuck/ui/rent/RentActivity.kt
  app/src/main/java/com/example/gaechuck/ui/rent/RentDetailFragment.kt
  app/src/main/java/com/example/gaechuck/ui/rent/RentMainFragment.kt
  app/src/main/java/com/example/gaechuck/ui/rent/RentWriteActivity.kt
  app/src/main/java/com/example/gaechuck/ui/rent/adapter/RentAdapter.kt
  app/src/main/java/com/example/gaechuck/ui/rent/viewmodel/RentViewModel.kt
  app/src/main/java/com/example/gaechuck/ui/setting/SettingActivity.kt
  app/src/main/java/com/example/gaechuck/ui/setting/adapter/SettingAdapter.kt
  app/src/main/java/com/example/gaechuck/ui/util/DialogFragment.kt
  app/src/main/res/drawable/custom_popup_background.xml
  app/src/main/res/drawable/style_popup.xml
  app/src/main/res/layout/activity_business.xml
  app/src/main/res/layout/activity_lose_url.xml
  app/src/main/res/layout/activity_lose_write.xml
  app/src/main/res/layout/activity_rent.xml
  app/src/main/res/layout/alert_detail_popup.xml
  app/src/main/res/layout/alert_popup.xml
  app/src/main/res/layout/fragment_lose_detail.xml
  app/src/main/res/menu/etc_menu.xml
  app/src/main/res/navigation/navigation_lose.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/style.xml
Labels: ✨feature, 👧🏻지희

#43 Refactor/#42 - 교내공지 관련 기능 수정
  app/src/main/java/com/example/gaechuck/api/ApiService.kt
  app/src/main/java/com/example/gaechuck/data/model/NoticeUnivModel.kt
  app/src/main/java/com/example/gaechuck/data/response/GetAllNoticeDataResponse.kt
  app/src/main/java/com/example/gaechuck/data/response/GetUnivNoticeDataResponse.kt
  app/src/main/java/com/example/gaechuck/data/response/GetUnivNoticeDetailResponse.kt
  app/src/main/java/com/example/gaechuck/repository/NoticeUnivRepository.kt
  app/src/main/java/com/example/gaechuck/ui/noticeuniv/NoticeUnivActivity.kt
  app/src/main/java/com/example/gaechuck/ui/noticeuniv/adaptor/NoticeUnivAdapter.kt
  app/src/main/java/com/example/gaechuck/ui/noticeuniv/viewmodel/NoticeUnivViewModel.kt
  app/src/main/res/layout/activity_notice_univ.xml
Labels: 🎨refactor, 👨🏻지원

#50 Refactor/#49
  app/src/main/assets/suttle_bus_route.json
  app/src/main/java/com/example/gaechuck/MainActivity.kt
  app/src/main/java/com/example/gaechuck/ui/bus/BusRouteActivity.kt
  app/src/main/java/com/example/gaechuck/ui/bus/viewmodel/BusRouteViewModel.kt
  app/src/main/java/com/example/gaechuck/ui/menu/CafeteriaMenuActivity.kt
  app/src/main/java/com/example/gaechuck/ui/menu/adaptor/CafeteriaMenuAdaptor.kt
  app/src/main/java/com/example/gaechuck/ui/menu/adaptor/DayButtonAdapter.kt
  app/src/main/res/drawable/menu_button.xml
  app/src/main/res/drawable/menu_button_selected.xml
  app/src/main/res/drawable/swipe.png
  app/src/main/res/layout/activity_bus_route.xml
  app/src/main/res/layout/activity_cafeteria_menu.xml
  app/src/main/res/layout/item_day_button.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/style.xml
Labels: 🎨refactor, 💄style, 👨🏻지원

#46 Feature/#45 - Connect Rent Search API
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/gaechuck/api/ApiService.kt
  app/src/main/java/com/example/gaechuck/data/request/BusinessPatchRequest.kt
  app/src/main/java/com/example/gaechuck/data/request/LosePatchRequest.kt
  app/src/main/java/com/example/gaechuck/data/request/RentPatchRequest.kt
  app/src/main/java/com/example/gaechuck/data/response/GetRentDataResponse.kt
  app/src/main/java/com/example/gaechuck/data/response/GetRentDetailResponse.kt
  app/src/main/java/com/example/gaechuck/data/response/PatchBusinessResponse.kt
  app/src/main/java/com/example/gaechuck/data/response/PatchLoseResponse.kt
  app/src/main/java/com/example/gaechuck/repository/BusinessRepository.kt
  app/src/main/java/com/example/gaechuck/repository/LoseRepository.kt
  app/src/main/java/com/example/gaechuck/repository/RentRepository.kt
  app/src/main/java/com/example/gaechuck/ui/business/BusinessActivity.kt
  app/src/main/java/com/example/gaechuck/ui/business/BusinessDetailFragment.kt
  app/src/main/java/com/example/gaechuck/ui/business/BusinessEditActivity.kt
  app/src/main/java/com/example/gaechuck/ui/business/viewmodel/BusinessViewModel.kt
  app/src/main/java/com/example/gaechuck/ui/lose/LoseActivity.kt
  app/src/main/java/com/example/gaechuck/ui/lose/LoseDetailFragment.kt
  app/src/main/java/com/example/gaechuck/ui/lose/LoseEditActivity.kt
  app/src/main/java/com/example/gaechuck/ui/lose/LoseWriteActivity.kt
  app/src/main/java/com/example/gaechuck/ui/lose/viewmodel/LoseViewModel.kt
  app/src/main/java/com/example/gaechuck/ui/rent/RentActivity.kt
  app/src/main/java/com/example/gaechuck/ui/rent/RentDetailFragment.kt
  app/src/main/java/com/example/gaechuck/ui/rent/RentEditActivity.kt
  app/src/main/java/com/example/gaechuck/ui/rent/RentMainFragment.kt
  app/src/main/java/com/example/gaechuck/ui/rent/adapter/RentAdapter.kt
  app/src/main/java/com/example/gaechuck/ui/rent/viewmodel/RentViewModel.kt
  app/src/main/res/layout/activity_business_write.xml
Labels: ✨feature, 🎨refactor, 👧🏻지희

#57 Refactor/#56 - 학식 관련 UI 수정
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/gaechuck/api/ApiService.kt
  app/src/main/java/com/example/gaechuck/data/response/PatchNoticeResponse.kt
  app/src/main/java/com/example/gaechuck/repository/CafeteriaMenuRepository.kt
  app/src/main/java/com/example/gaechuck/ui/menu/CafeteriaMenuActivity.kt
  app/src/main/java/com/example/gaechuck/ui/menu/adaptor/DayButtonAdapter.kt
  app/src/main/java/com/example/gaechuck/ui/menu/adaptor/GridCafeteriaAdapter.kt
  app/src/main/java/com/example/gaechuck/ui/menu/viewmodel/CafeteriaMenuViewModdel.kt
  app/src/main/java/com/example/gaechuck/ui/noticecouncil/NoticeCouncilActivity.kt
  app/src/main/java/com/example/gaechuck/ui/noticecouncil/NoticeCouncilDetailActivity.kt
  app/src/main/java/com/example/gaechuck/ui/noticecouncil/NoticeCouncilUpdateActivity.kt
  app/src/main/java/com/example/gaechuck/ui/noticecouncil/adaptor/ImageAdapter.kt
  app/src/main/java/com/example/gaechuck/ui/noticecouncil/adaptor/NoticeCouncilAdapter.kt
  app/src/main/java/com/example/gaechuck/ui/noticeuniv/adaptor/NoticeUnivAdapter.kt
  app/src/main/res/drawable/week_button.xml
  app/src/main/res/drawable/week_button_normal.xml
  app/src/main/res/drawable/week_button_selected.xml
  app/src/main/res/layout/activity_cafeteria_menu.xml
  app/src/main/res/layout/activity_notice_council.xml
  app/src/main/res/layout/activity_notice_council_detail.xml
  app/src/main/res/layout/fragment_notice_council.xml
  app/src/main/res/layout/fragment_notice_council_detail.xml
  app/src/main/res/layout/fragment_notice_univ.xml
  app/src/main/res/layout/item_day_button.xml
  app/src/main/res/layout/item_menu_grid.xml
  app/src/main/res/layout/item_menu_header.xml
  app/src/main/res/values/colors.xml
Labels: 🎨refactor, 💄style, 👨🏻지원

#58 Feature/#55 - url API 연결
  app/src/main/java/com/example/gaechuck/api/ApiService.kt
  app/src/main/java/com/example/gaechuck/data/request/UrlChangeRequest.kt
  app/src/main/java/com/example/gaechuck/data/response/PostUrlResponse.kt
  app/src/main/java/com/example/gaechuck/ui/business/BusinessMainFragment.kt
  app/src/main/java/com/example/gaechuck/ui/lose/LoseDetailFragment.kt
  app/src/main/java/com/example/gaechuck/ui/lose/LoseMainFragment.kt
  app/src/main/java/com/example/gaechuck/ui/lose/LoseUrlChangeActivity.kt
  app/src/main/java/com/example/gaechuck/ui/lose/viewmodel/LoseViewModel.kt
  app/src/main/java/com/example/gaechuck/ui/rent/RentDetailFragment.kt
  app/src/main/java/com/example/gaechuck/ui/rent/RentMainFragment.kt
  app/src/main/java/com/example/gaechuck/ui/rent/viewmodel/RentViewModel.kt
  app/src/main/res/layout/fragment_rent_main.xml
Labels: ✨feature, 👧🏻지희, 💄style

#61 Feature/#59 - 수정 API 이미지 오류 해결 및 로그인 토큰 관리
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/gaechuck/api/ApiService.kt
  app/src/main/java/com/example/gaechuck/repository/BusinessRepository.kt
  app/src/main/java/com/example/gaechuck/repository/LoseRepository.kt
  app/src/main/java/com/example/gaechuck/repository/RentRepository.kt
  app/src/main/java/com/example/gaechuck/ui/business/BusinessActivity.kt
  app/src/main/java/com/example/gaechuck/ui/business/BusinessEditActivity.kt
  app/src/main/java/com/example/gaechuck/ui/business/BusinessWriteActivity.kt
  app/src/main/java/com/example/gaechuck/ui/business/viewmodel/BusinessViewModel.kt
  app/src/main/java/com/example/gaechuck/ui/lose/LoseWriteActivity.kt
  app/src/main/java/com/example/gaechuck/ui/lose/viewmodel/LoseViewModel.kt
  app/src/main/java/com/example/gaechuck/ui/menu/CafeteriaMenuActivity.kt
  app/src/main/java/com/example/gaechuck/ui/noticecouncil/NoticeCouncilActivity.kt
  app/src/main/java/com/example/gaechuck/ui/rent/RentActivity.kt
  app/src/main/java/com/example/gaechuck/ui/rent/viewmodel/RentViewModel.kt
  app/src/main/res/layout/activity_business_write.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_notice_council.xml
  app/src/main/res/layout/activity_notice_univ.xml
  app/src/main/res/layout/fragment_photo_add.xml
  app/src/main/res/layout/fragment_photo_add2.xml
Labels: 🐛 bug, ✨feature, 🎨refactor, 👧🏻지희
